In [1]:
import numpy as np

In [5]:
for i in range (10):
    pass
max([1])
np.sqrt(5)

2.23606797749979

In [6]:
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
a.shape

(5, 3)

In [9]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [13]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
print(c[1,1])
# If i want the first 
print(c[1,:])
print(c[:,1])
print(c[1,1:])
print(c.shape)
print(c[-1,:])
print(c[c.shape[0]-1,:])

5
[4 5 6]
[2 5]
[5 6]
(2, 3)
[4 5 6]
[4 5 6]


In [22]:
a = np.zeros((5,3))
a[1,1]=777
a[-2:,-2:]=1
print(a)

[[  0.   0.   0.]
 [  0. 777.   0.]
 [  0.   0.   0.]
 [  0.   1.   1.]
 [  0.   1.   1.]]
